---
job_name: "Cool FL experiment"
# project name should not have spaces
project: cool_project 

data:
  dataset: "cifar10"
  # partition_folder: 
  
code: 
  path: "/home/faustiar/fl-testbed/user_code_example"
  client:
    entrypoint: client.py
    args: ""
  server: 
    entrypoint: server.py
    args: "--num_clients=2 --num_rounds=1"

devices:
  - device_type: JetsonAGXOrin
    count: 1
  - device_type: JetsonOrinNano
    count: 1