apiVersion: v1
kind: Pod
metadata:
  name: fl-client
spec:
  containers:
  - name: fl-client
    image: flserver:5000/fltb_test/generic
    command: ["sleep", "1000"]
  imagePullSecrets:
    - name: regcred
  nodeSelector:
    kubernetes.io/hostname: lp3