- name: Enable power cap read permissions
  block:
  - name: Copy services
    ansible.builtin.copy:
      src: "services/rapl/powercap_read_perm.service"
      dest: "/etc/systemd/system/"
      owner: root
      group: root
      mode: '0644'

  - name: Enable and start service
    # For some reason I kept getting this error:
    # ERROR! couldn't resolve module/action 'ansible.builtin.systemd_service'. This often indicates a misspelling, missing collection, or incorrect module path.
    # ansible.builtin.systemd_service:
      # name: powercap_read_perm
      # enabledr: true
      # state: started
    ansible.builtin.shell:
      cmd: systemctl enable --now powercap_read_perm
  when: "'lattePandas' in group_names"