project: colext_example # project name should not have spaces
job_name: "SOTA FL experiment"

deployer: local_py
code:
  python_version: "3.10"
  client:
    command: >-
      python3 client.py
      --flserver_address=${COLEXT_SERVER_ADDRESS}
      --max_step_count=1000

  server:
    command: >-
      python3 server.py
      --num_clients=${COLEXT_N_CLIENTS}
      --num_rounds=3

devices:
  - { device_type: JetsonAGXOrin,  count: 1 }
  # - { device_type: JetsonOrinNano, count: 2 }
  # - { device_type: JetsonXavierNX, count: 2 }
  # - { device_type: JetsonNano, count: 6 }
  # - { device_type: LattePandaDelta3, count: 1 }
  - { device_type: OrangePi5B, count: 1 }

# Monitoring defaults
# monitoring:
#   live_metrics: True # True/False
#   push_interval: 10 # in seconds
#   scraping_interval: 0.3 # in seconds
