- name: Configure hostname to match ansible inventory
  # Note that this does not set /etc/hosts!
  ansible.builtin.hostname:
    name: "{{inventory_hostname}}"

- name: Ensure /etc/hosts has correct hostname
  ansible.builtin.replace:
    path: /etc/hosts
    after: '127\.0\.0\.1\s*localhost'
    regexp: '127\.0\.1\.1\s*.*'
    replace: '127.0.1.1\t{{inventory_hostname}}'

- name: Install packages
  ansible.builtin.import_tasks: install_packages.yaml

- name: Configure microk8s
  ansible.builtin.import_tasks: configure_microk8s.yaml

- name: Configure datasets
  ansible.builtin.import_tasks: configure_datasets.yaml

# Disable default graphical interface?