# Service to expose RabbitMQ AMQP port
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    cotext-component: message-broker
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 6942
    targetPort: 6942
    name: amqp
  - port: 15672
    targetPort: 15672
    name: management