#  sudo snap install microk8s --classic --channel=1.29
- name: Install microk8s
  community.general.snap:
    name: microk8s
    classic: true
    channel: 1.29

- name: Add local user to microk8s group
  ansible.builtin.user:
    name: "{{ansible_user}}"
    groups: microk8s
    append: yes

- name: Rest SSH connection to see new group
  meta: reset_connection

- name: Ensure microk8s is enabled and running
  ansible.builtin.service:
    name: snap.microk8s.daemon-kubelite
    enabled: true
    state: started

- name: Configure private registry in microk8s
  ansible.builtin.import_tasks: configure_private_registry.yaml

- name: Configure containerd
  ansible.builtin.import_tasks: configure_containerd.yaml
  when: "'jetsons' in group_names"

- name: Add SBC to kubernetes pool
  become: false
  ansible.builtin.shell:
    cmd: "microk8s join {{microk8s.host}}/{{microk8s.token}} --worker"
  when: "'outOfNetwork' not in group_names"