--- 
- name: "Configure SBC"
  hosts: devices
  become: true
  roles:
    - role: base_sbc
      vars:
        auth:
          key: "{{ lookup('file', '/home/' + lookup('env', 'USER') + '/.ssh/id_rsa.pub') }}"
        ntp:
          ip: 10.0.0.100 # flserver
        std_datasets:
          src_path: /fltb/datasets/
          dest_path: /fltb/datasets/
        pytorch_datasets:
          path: /fltb/pytorch_datasets/

    - role: microk8s_worker
      vars:
        microk8s: 
          host: 10.0.0.100:25000
          token: a1ef095d59c2fef65d5263090e678cc0/6dd903933278
          # Generated a valid token with the duration of 1 year
          # microk8s add-node --token a1ef095d59c2fef65d5263090e678cc0 -l 31536000
          # /var/snap/microk8s/current/credentials/cluster-tokens.txt 
        priv_registry: 
          hostname: flserver
          internal_ip: 10.0.0.100
          port: 5000
